/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.SucursalController;
import controlador.ed.lista.exception.PosicionException;
import controlador.ed.lista.exception.VacioException;
import controlador.util.Utilidades;
import java.awt.Frame;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vista.ModeloTablas.ModeloTablaVentas;

/**
 *
 * @author alyce
 */
public class FrmVentasSucursales extends javax.swing.JDialog {
    private ModeloTablaVentas mv = new ModeloTablaVentas();
    private SucursalController sc ;
    //private Utilidades u = new Utilidades();
    private int fila = -1;

    /**
     * Creates new form FrmVentasSucursales
     */
    public FrmVentasSucursales(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public FrmVentasSucursales(java.awt.Frame parent, boolean modal, SucursalController scv) {
        super(parent, modal);
        initComponents();
        this.sc = scv;
        lblNombreSucursak.setText(scv.getSucursal().getNombre());
        
        limpiar();
    }
    
     private void cargarTabla() {
            mv.setDatos(sc.getSucursal().getVentas());
            tblTabla1.setModel(mv);
            tblTabla1.updateUI();
            
    }
     
     private void cargarVenta(){
         fila = tblTabla1.getSelectedRow();
         if (fila >= 0) {
             try {
                 //this.sc.setVenta(mv.getDatos().get(fila));
                 this.sc.setVenta(this.sc.getSucursal().getVentas().get(fila));
             } catch (VacioException ex) {
                 Logger.getLogger(FrmVentasSucursales.class.getName()).log(Level.SEVERE, null, ex);
             } catch (PosicionException ex) {
                 Logger.getLogger(FrmVentasSucursales.class.getName()).log(Level.SEVERE, null, ex);
             }
             txtCantidadVentas.setText(this.sc.getVenta().getValor().toString());
             lblMesEscogido.setText(this.sc.getVenta().getMes().toString());
             cargarTabla();
             
             System.out.println("***********************************");
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una venta de la tabla","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
        private void limpiar() {
        this.sc.setVenta(null);
        txtCantidadVentas.setText("");
        lblMesEscogido.setText("");
        fila = -1;
        cargarTabla();
     }
        
        private void modificar(){
        if (!txtCantidadVentas.getText().trim().isEmpty() && !lblMesEscogido.getText().isEmpty()) {
            try {
            this.sc.guardarVentas(fila,Double.parseDouble(txtCantidadVentas.getText()));
            this.limpiar();
            JOptionPane.showMessageDialog(null, "Se ha actualizado","OK",JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }else {
            JOptionPane.showMessageDialog(null, "Llene todos los campos","Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombreSucursak = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidadVentas = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblMesEscogido = new javax.swing.JLabel();
        btnSelect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabla1 = new javax.swing.JTable();
        btnGuardarTodo = new javax.swing.JButton();
        btnAllSucursales = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblMesBajo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblCantidadMesBajo = new javax.swing.JLabel();
        btnGuardarTodo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(191, 232, 174));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informacion Sucursales"));

        jLabel1.setText("Nombre Sucursal: ");

        lblNombreSucursak.setText("Nombre sucursal");
        lblNombreSucursak.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Cantidad Ventas");

        txtCantidadVentas.setText("<<0.00>>");

        btnGuardar.setBackground(new java.awt.Color(175, 218, 157));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel2.setText("Mes: ");

        lblMesEscogido.setText("<MES ESCOGIDO>");

        btnSelect.setBackground(new java.awt.Color(175, 218, 157));
        btnSelect.setText("Seleccionar");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMesEscogido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(146, 146, 146))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreSucursak, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnSelect))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblNombreSucursak, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnGuardar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblMesEscogido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCantidadVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSelect)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tblTabla1.setBackground(new java.awt.Color(191, 232, 174));
        tblTabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTabla1);

        btnGuardarTodo.setBackground(new java.awt.Color(175, 218, 157));
        btnGuardarTodo.setText("Guardar Todo");
        btnGuardarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTodoActionPerformed(evt);
            }
        });

        btnAllSucursales.setBackground(new java.awt.Color(175, 218, 157));
        btnAllSucursales.setText("Todas las sucursales");
        btnAllSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllSucursalesActionPerformed(evt);
            }
        });

        jLabel4.setText("EL mes de ");

        lblMesBajo.setText(".................");

        jLabel5.setText("se registraron las menores ventas teniendo como resultado :");

        lblCantidadMesBajo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCantidadMesBajo.setText("00,00");

        btnGuardarTodo1.setBackground(new java.awt.Color(175, 218, 157));
        btnGuardarTodo1.setText("Mostrar");
        btnGuardarTodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTodo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMesBajo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(lblCantidadMesBajo))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardarTodo)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarTodo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAllSucursales)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblMesBajo)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(lblCantidadMesBajo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarTodo)
                    .addComponent(btnAllSucursales)
                    .addComponent(btnGuardarTodo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTodoActionPerformed
        try {
            // TODO add your handling code here:
            Utilidades.guardarEnJson(sc,"data/csa.json");
        } catch (IOException ex) {
            Logger.getLogger(FrmVentasSucursales.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnGuardarTodoActionPerformed

    private void btnAllSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllSucursalesActionPerformed
        // TODO add your handling code here:
//        int fila = tblTabla1.getSelectedRow();
//        if (fila >= 0) {
//            if (mv.getDatos()!= null) {
//                //this.sc.setSucursal(md.getLista());
//                new FrmMayoresVentas(null, true, this.sc).setVisible(true);
//                 //this.control.setSucursal(modelo.getDatos()[fila]);
//                cargarTabla();
//                tblTabla1.clearSelection();
//            }else{
//                JOptionPane.showMessageDialog(null, "Ingrese un nombre a la sucursal","Error",JOptionPane.ERROR_MESSAGE);
//            }
//        }else {
//            JOptionPane.showMessageDialog(null, "Seleccione una sucursal de la tabla","Error",JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_btnAllSucursalesActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        modificar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
            // TODO add your handling code here:
            cargarVenta();
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnGuardarTodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTodo1ActionPerformed
        try {
            // TODO add your handling code here:
            Utilidades.cargarJson(SucursalController.class, "data/csa.json");
        } catch (IOException ex) {
            Logger.getLogger(FrmVentasSucursales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarTodo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentasSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentasSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentasSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentasSucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmVentasSucursales dialog = new FrmVentasSucursales(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllSucursales;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarTodo;
    private javax.swing.JButton btnGuardarTodo1;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidadMesBajo;
    private javax.swing.JLabel lblMesBajo;
    private javax.swing.JLabel lblMesEscogido;
    private javax.swing.JLabel lblNombreSucursak;
    private javax.swing.JTable tblTabla1;
    private javax.swing.JTextField txtCantidadVentas;
    // End of variables declaration//GEN-END:variables
}
